version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-group-manager
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_USERNAME=${BOT_USERNAME}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUDO_USERS=${SUDO_USERS}
      - REDIS_URL=redis://redis:6379/0
      - WEBHOOK_URL=${WEBHOOK_URL:-}
      - WEBHOOK_PATH=${WEBHOOK_PATH:-/webhook}
      - WEBAPP_HOST=0.0.0.0
      - WEBAPP_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    container_name: telegram-bot-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bot-network
    command: redis-server --appendonly yes
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

volumes:
  redis_data:
    driver: local

networks:
  bot-network:
    driver: bridge
